version: '3'
services:

  tests:
    links:
      - redis-test
    depends_on:
      - redis-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    command: >
      npm run test:redis

  redis-test:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./test/redis/data:/data
      - ./test/redis/redis.conf:/redis.conf
    command: >
      redis-server /redis.conf
