destroyAllTokensAtStartup: true

redis:
  namespace: doorkeeper.test
  client:
    url: "redis://redis-test:16379"

users:
  staticUsersFile: config/test-users.json

token:
  login:
    lastLoginExpire: 1
  session:
    expiresIn: 1s
